### ISSUE TITLE
teresco.org server off the network

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/UserData#1135]
Placing this here for lack of a better option.  What was supposed to be a seamless upgrade (of which I learned only minutes before it happened) to the network where the server housing TM is attached resulted in the server being unable to obtain an IP address.  I hope we will be able to resolve it tonight, but there's potential for a lengthy down time (days to weeks) if significantly new arrangements need to be made for the server. @si404 @rickmastfan67 @michihdeu @yakra @ajfroggie @mapcat @ovoss @Duke87ofST

**Comment by jteresco** [comment]
I am planning to move the server to my house this morning, hoping it can get a public IP address and that our standard cable modem service is enough to handle the load at least temporarily.  Even if so, it will be a while once I update DNS for the new address to propagate.

**Comment by jteresco** [comment]
We seem to be a victim of the change from a Time Warner Cable "legacy" configuration to the "new improved" Spectrum service.  The option to move to my house won't help...  Hoping to be able to buy a second public IP, at least temporarily to get back online before finding a long term solution.  I am losing confidence in the ability to get a quick fix.

**Comment by rickmastfan67** [comment]
I posted a quick thread about this over @ AARoads w/ a link to here so others will know about it.
https://www.aaroads.com/forum/index.php?topic=21961.0

**Comment by jteresco** [comment]
Second IP option is not feasible short term.  Looking into a new temporary location.

**Comment by jteresco** [comment]
Server has moved to my office.  I now need to see if I can get it on the network here and reconfigure what I need to reconfigure.

**Comment by jteresco** [comment]
It's up on the network and services are running, but it will take a while for the new IP addresses of both the name server and the web server to propagate.

**Comment by yakra** [comment]
Good to know. Thanks for all your work in dealing with this & getting it back online.

**Comment by jteresco** [comment]
Earlier change to tell my domain name provider about the new IP address didn't seem to go through.  Trying again.  The good news is that everything is up and running.  The bad news is that the DNS world still wants to go to the old address.

**Comment by jteresco** [comment]
OK, good news.  I logged into a machine that hasn't cached any teresco.org domain information recently and it gets the new site.  It should only be a matter of time.  Probably as much as 24 hours in some cases.

**Comment by the-spui-ninja** [comment]
I was just able to see it from my computer as well.

**Comment by michihdeu** [comment]
It works for me too! Thanks! 👍

**Comment by yakra** [comment]
Working here.

**Comment by ajfroggie** [comment]
On travel so missed this initially.  Still not working on Verizon Wireless, but I was able to get to it by stopping at a Starbucks outside Hartford and using their WiFi.

**Comment by si404** [comment]
Wasn't working at home or on 4G for me.

**Comment by ssoworld** [comment]
back for me.

**Comment by ovoss** [comment]
Just got back home. Everything I've checked so far (the forum and the HB) is working for me.

**Comment by jteresco** [comment]
I think we're good for now.
