### ISSUE TITLE
Newline characters in list files

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/UserData#2174]
There's been some discussion recently about newline characters in both list files and wpt files.  At the moment, there seem to be no list files that cause problems with the site update process, even though there are a some different things going on in various files.  FYI, @yakra, here's what the "file" command on my Mac says about the current collection of list files:

<pre>
1.list:                  ASCII text, with CRLF line terminators
1995hoo.list:            ASCII text, with CRLF line terminators
25or6to4.list:           ASCII text, with CRLF line terminators
7_8.list:                ASCII text, with CRLF line terminators
Aseluit.list:            ASCII text, with CRLF line terminators
Beerman.list:            UTF-8 Unicode (with BOM) text, with CRLF line terminators
Chikara.list:            ASCII text, with CRLF line terminators
ChrisZwolle.list:        ASCII text, with CRLF line terminators
DJCane.list:             ASCII text, with CRLF line terminators
JamesMD.list:            ASCII text, with CRLF line terminators
Qiviuq.list:             ASCII text, with CRLF line terminators
ThelwallViaduct.list:    ASCII text, with CRLF line terminators
Ugnaught2.list:          ASCII text, with CRLF line terminators
aaroads.list:            ASCII text, with CRLF line terminators
afarina.list:            UTF-8 Unicode text, with CRLF line terminators
along.list:              ASCII text, with CRLF line terminators
angelsfreeek.list:       ASCII text
atsiatas.list:           ASCII text
barefoot_driver.list:    ASCII text, with CRLF line terminators
based8.list:             ASCII text
baugh17.list:            ASCII text, with CRLF line terminators
bejacob.list:            ASCII text, with CRLF line terminators
benjamingrove47.list:    ASCII text, with CRLF line terminators
bhemphill.list:          ASCII text, with CRLF line terminators
bickendan.list:          ASCII text, with CRLF line terminators
bm7.list:                ASCII text, with CRLF line terminators
bobcobb.list:            ASCII text, with CRLF, LF line terminators
bogdymol.list:           ASCII text, with CRLF, LF line terminators
boris.list:              ASCII text, with CRLF line terminators
bubaclex.list:           ASCII text, with CRLF line terminators
bulldog1979.list:        ASCII text, with CRLF line terminators
cabiness42.list:         ASCII text, with CRLF line terminators
capn.list:               ASCII text, with CRLF line terminators
chaddean.list:           data
charliezeb.list:         ASCII text, with CRLF line terminators
cinx.list:               ASCII text, with CRLF line terminators
cl94.list:               ASCII text, with CRLF line terminators
clark1mt.list:           ASCII text, with CRLF line terminators
clong.list:              ASCII text, with CRLF line terminators
codyg1985.list:          ASCII text
compdude787.list:        ASCII text, with CRLF line terminators
cougar1989.list:         ASCII text, with CRLF line terminators
crosboro7.list:          ASCII text, with CRLF, LF line terminators
cyhighways.list:         ASCII text
dantheman.list:          ASCII text, with CRLF line terminators
dave1693.list:           ASCII text, with CRLF line terminators
dcharlie.list:           ASCII text, with CRLF line terminators
dcm55343.list:           ASCII text, with CRLF line terminators
dctransit.list:          ASCII text, with CRLF line terminators
deathtopumpkins.list:    ASCII text, with CRLF line terminators
dfilpus.list:            ASCII text, with CRLF line terminators
dgolub.list:             ASCII text, with CRLF line terminators
dharwood.list:           ASCII text, with CRLF line terminators
dnthrox.list:            ASCII text, with CRLF line terminators
dognm16.list:            ASCII text, with CRLF line terminators
dough4872.list:          ASCII text, with CRLF line terminators
drebbin37.list:          ASCII text, with CRLF line terminators
drfrankenstein.list:     ASCII text
dsaneus.list:            ESP archive data
dscarroll.list:          ASCII text, with CRLF, CR line terminators
dsm4cy.list:             ASCII text
duke87.list:             ASCII text, with CRLF line terminators
dylucktrocket.list:      ASCII text, with CRLF line terminators
eidderf.list:            ASCII text
electronym.list:         ASCII text, with CRLF line terminators
epzik8.list:             ASCII text, with CRLF line terminators
es92.list:               ASCII text, with CRLF line terminators
eth.list:                ASCII text
eucitizen.list:          ASCII text, with CRLF line terminators
extremebandman.list:     ASCII text, with CRLF line terminators
finnedude.list:          UTF-8 Unicode text
foresthills93.list:      ASCII text, with CRLF line terminators
froggie.list:            ASCII text, with CRLF line terminators
georgiaroadgeek.list:    ASCII text, with CRLF, LF line terminators
gimmicks.list:           ASCII text, with CRLF line terminators
gman2337.list:           ASCII text, with CRLF line terminators
golubcar.list:           ASCII text
gpw.list:                ASCII text, with CRLF, LF line terminators
griffith.list:           ASCII text, with CRLF line terminators
happy5214.list:          ASCII text
harvey.list:             ASCII text
highplainstrvlr.list:    UTF-8 Unicode (with BOM) text, with CRLF line terminators
hoopitypoop.list:        ASCII text, with CRLF line terminators
hoss6884.list:           ASCII text, with CRLF line terminators
htm_duke.list:           ASCII text, with CRLF line terminators
hurricanehink.list:      ASCII text, with CRLF line terminators
ibexto.list:             ASCII text, with CRLF line terminators
imgoph.list:             ASCII text
inagaddadavida.list:     ASCII text, with CRLF line terminators
intelati49.list:         ASCII text, with CRLF line terminators
intheam.list:            ASCII text, with CRLF line terminators
iowahighways.list:       ASCII text, with CRLF line terminators
jackgaynor.list:         ASCII text, with CRLF line terminators
jayhawkco.list:          ASCII text, with CRLF line terminators
jbum86MASTER.list:       ASCII text
jeffm.list:              ASCII text, with CRLF line terminators
jerseyman4.list:         ASCII text, with CRLF line terminators
jimvette.list:           ASCII text, with CRLF line terminators
jjbers.list:             ASCII text, with CRLF line terminators
johninkingwood.list:     ASCII text, with CRLF line terminators
jonfmorse.list:          ASCII text, with CRLF line terminators
jordancarrpeterson.list: ASCII text
jpinyan.list:            ASCII text, with CRLF line terminators
jstalica.list:           ASCII text, with CRLF line terminators
julmac.list:             ASCII text, with CRLF line terminators
justjake.list:           ASCII text, with CRLF line terminators
jweeks.list:             ASCII text, with CRLF line terminators
jwood.list:              ASCII text, with CRLF line terminators
keithcavey.list:         ASCII text, with CRLF, LF line terminators
kjslaughter.list:        UTF-8 Unicode (with BOM) text, with very long lines, with CRLF line terminators
klundgren.list:          ASCII text, with CRLF line terminators
kramer.list:             ASCII text, with CRLF, LF line terminators
kurzov.list:             ASCII text, with CRLF line terminators
lakewy17.list:           ASCII text
lamsalfl.list:           ASCII text, with CRLF line terminators
lkefct.list:             ASCII text, with CRLF line terminators
lowenbrau.list:          data
mapcat.list:             ASCII text, with CRLF line terminators
mapmikey.list:           ASCII text, with CRLF line terminators
mariethefoxy.list:       ASCII text, with CRLF line terminators
markkos1992.list:        ASCII text, with CRLF line terminators
master_son.list:         ASCII text
mc49399.list:            ASCII text, with CRLF line terminators
mefailenglish.list:      ASCII text, with CRLF line terminators
mepaulrye.list:          ASCII text, with CRLF line terminators
michih.list:             ASCII text
mikeandkristie.list:     ASCII text
mirage45331.list:        ASCII text
mojavenc.list:           ASCII text, with CRLF line terminators
morriswa.list:           ASCII text, with CRLF line terminators
moshitea.list:           ASCII text
mr_matt_k.list:          ASCII text, with CRLF line terminators
mvak36.list:             ASCII text, with CRLF line terminators
mwasleski.list:          ASCII text, with CRLF line terminators
myselfalso.list:         ASCII text, with CRLF, LF line terminators
navigator.list:          ASCII text, with CRLF line terminators
neilbert.list:           ASCII text, with CRLF line terminators
neroute2.list:           ASCII text
new_friends_gr.list:     ASCII text, with CRLF line terminators
ngrier.list:             ASCII text, with CRLF line terminators
niels.list:              ASCII text, with CRLF, LF line terminators
njroadhorse.list:        ASCII text, with CRLF line terminators
noelbotevera.list:       ASCII text, with CRLF line terminators
norheim.list:            ASCII text, with CRLF line terminators
nrm1221.list:            ASCII text, with CRLF line terminators
ntallyn.list:            ASCII text, with CRLF line terminators
ohroadscholar.list:      ASCII text, with CRLF line terminators
okroads.list:            ASCII text, with CRLF line terminators
opspe.list:              ASCII text, with CRLF line terminators
oscar.list:              ASCII text, with CRLF line terminators
osu97gp.list:            ASCII text, with CRLF line terminators
osu_lsu.list:            ASCII text, with CRLF line terminators
paddy.list:              ASCII text, with CRLF line terminators
pahighways.list:         ASCII text, with CRLF line terminators
panda80.list:            ASCII text, with CRLF line terminators
paulthemapguy.list:      ASCII text, with CRLF line terminators
peperodriguez2710.list:  ESP archive data
philimon.list:           UTF-8 Unicode text
philman.list:            ASCII text, with CRLF line terminators
pianocello130.list:      ASCII text, with CRLF line terminators
pnrrth.list:             ASCII text
polabare.list:           ASCII text
presidentman.list:       ASCII text, with CRLF line terminators
quidditch33.list:        ASCII text, with CRLF line terminators
radison.list:            ASCII text
ran4sh.list:             ASCII text, with CRLF line terminators
rebelgtp.list:           ASCII text, with CRLF line terminators
regoarrarr.list:         ASCII text, with CRLF line terminators
rgentry.list:            ASCII text
rickmastfan67.list:      ASCII text
riehlj.list:             ASCII text, with CRLF line terminators
riiga.list:              ASCII text
rlee.list:               ASCII text, with CRLF line terminators
roadgeek99.list:         ASCII text, with CRLF line terminators
roadgeek_adam.list:      ASCII text, with CRLF line terminators
roadguy2.list:           ASCII text
robringstad.list:        ASCII text, with CRLF line terminators
roukan.list:             ASCII text, with CRLF line terminators
route56.list:            ASCII text, with CRLF line terminators
rschen7754.list:         ASCII text
sammi.list:              ASCII text
sbeaver44.list:          ASCII text
scheidler.list:          ASCII text, with CRLF line terminators
scott_stieglitz.list:    ASCII text, with CRLF, LF line terminators
sercamaro.list:          ASCII text, with CRLF, LF line terminators
sfisher.list:            ASCII text, with CRLF line terminators
si404.list:              ASCII text
sipes23.list:            ASCII text
skatcher.list:           ASCII text, with CRLF line terminators
skoutr1.list:            ASCII text, with CRLF line terminators
slorydn1.list:           ASCII text, with CRLF line terminators
sneezy.list:             ASCII text
snowedin.list:           ASCII text, with CRLF line terminators
snowmatt8.list:          UTF-8 Unicode (with BOM) text, with CRLF line terminators
sounderbruce.list:       ASCII text
spinoza.list:            ASCII text, with CRLF line terminators
squatchis.list:          ASCII text, with CRLF, LF line terminators
ssgtcrusty.list:         ASCII text, with CRLF line terminators
superblu2007.list:       ASCII text, with CRLF line terminators
synkdorbit.list:         ASCII text, with CRLF line terminators
tag42481.list:           ASCII text, with CRLF line terminators
tarheel61581.list:       ASCII text
tbwillie.list:           ASCII text, with CRLF line terminators
tckma.list:              ASCII text, with CRLF line terminators
terescoj.list:           ASCII text, with CRLF line terminators
terminal_moraine.list:   ASCII text, with CRLF line terminators
the_spui_ninja.list:     ASCII text, with CRLF line terminators
thefxexpert.list:        ASCII text, with CRLF line terminators
thehighwayman3561.list:  ASCII text, with CRLF line terminators
thing342.list:           ASCII text
tikester.list:           ASCII text, with CRLF line terminators
tjj25.list:              ASCII text, with CRLF line terminators
tomhart.list:            ASCII text, with CRLF line terminators
twinsfan87.list:         ASCII text, with CRLF line terminators
ua747sp.list:            ASCII text
usaidhello.list:         ASCII text, with CRLF line terminators
valedc03ls.list:         ASCII text, with CRLF line terminators
vcap36.list:             ASCII text
vdeane.list:             UTF-8 Unicode text, with CRLF line terminators
verruckte_dan.list:      ASCII text, with CRLF line terminators
verumsolum.list:         ASCII text
vespertine.list:         UTF-8 Unicode (with BOM) text, with CRLF line terminators
vinoman64.list:          ASCII text, with CRLF line terminators
voyager105.list:         ASCII text, with CRLF line terminators
w9tam.list:              ASCII text
wadsteckel.list:         ASCII text, with CRLF line terminators
whopperman.list:         ASCII text, with CRLF, CR line terminators
wphiii.list:             ASCII text
xcvxcvxcv.list:          ASCII text
xorodejon.list:          ASCII text
yakra.list:              ASCII text
yipcoyote.list:          ASCII text, with CRLF line terminators
</pre>

**Comment by yakra** [comment]
Excellent, thanks for this.
whopperman.list was a good test for robustness in the C++ version.
I made note of lowenbrau.list [here](https://github.com/TravelMapping/DataProcessing/issues/41#issuecomment-440441040), but not what exactly was in the file where. I see that chaddean.list is similarly flagged as `data`. These merit a closer look in a hex editor.
I've not yet done anything in the C++ version to handle the UTF-8 Unicode files; more than likely these ones prevent the first line from being parsed.
```
Beerman.list:           UTF-8 Unicode (with BOM) text, with CRLF line terminators
afarina.list:           UTF-8 Unicode text, with CRLF line terminators
chaddean.list:          data
dsaneus.list:           ESP archive data
finnedude.list:         UTF-8 Unicode text
highplainstrvlr.list:   UTF-8 Unicode (with BOM) text, with CRLF line terminators
kjslaughter.list:       UTF-8 Unicode (with BOM) text, with very long lines, with CRLF line terminators
lowenbrau.list:         data
peperodriguez2710.list: ESP archive data
philimon.list:          UTF-8 Unicode text
snowmatt8.list:         UTF-8 Unicode (with BOM) text, with CRLF line terminators
vdeane.list:            UTF-8 Unicode text, with CRLF line terminators
vespertine.list:        UTF-8 Unicode (with BOM) text, with CRLF line terminators
```

**Comment by yakra** [comment]
> I've not yet done anything in the C++ version to handle the UTF-8 Unicode files; more than likely these ones prevent the first line from being parsed.

Surprisingly, none of these files (even chaddean.list) differed between the Python & C++ versions, except for lowenbrau.list as noted in #41.

I'm curious to see what's happening in these files that flags them as UTF-8, and how it is that siteupdate.cpp copes with them, which wasn't intentional.

These merit a closer look in a hex editor, along with chaddean.list, to see what flags it as data.

**Comment by yakra** [comment]
* [UTF-8 byte order marks](https://github.com/TravelMapping/DataProcessing/issues/215) can produce .log errors, and potentially cause the first line to not be processed
  - `Incorrect format line: ï»¿` [Beerman.log](http://travelmapping.net/logs/users/Beerman.log)
  - `Unknown region/highway combo in line: ï»¿HI I-H1 8B 13B` [highplainstrvlr.log](http://travelmapping.net/logs/users/highplainstrvlr.log)
  - `Incorrect format line: ï»¿2019/04/10` [snowmatt8.log](http://travelmapping.net/logs/users/snowmatt8.log)
  - etc.
* > I see that chaddean.list is similarly flagged as `data`

  - Stray non-ascii character in the middle of a point label:
    FL44 FL19`0x1F`_N US441_S

**Comment by FinneDude** [comment]
> I'm curious to see what's happening in these files that flags them as UTF-8

In my case the comments contain non-ascii characters.

**Comment by yakra** [comment]
https://github.com/TravelMapping/DataProcessing/pull/309 strips out the byte order mark.
Line terminator hijinks were squared away by the time C++ region-splitting support was added.
Appears there's nothing left to do here.

I would close this, but it appears I can no longer do so in this repo?
